-- Authentic wicked-estate SQLite store dump (subset), for adapter tests.
-- Generated by: wicked-estate index tests/fixtures/estate_repo   (wicked-estate 0.14.4)
-- Tables dumped: symbols, nodes, edges, meta, files, unresolved_refs
-- (FTS/content/cache/annotations omitted — not part of the estate_db.py read contract).
-- meta.indexed_root and repo_* provenance sanitized (repo-relative / empty).
/* WARNING: Script requires that SQLITE_DBCONFIG_DEFENSIVE be disabled */
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE files (
  path    TEXT PRIMARY KEY,
  digest  TEXT NOT NULL DEFAULT '',
  git_sha TEXT
);
INSERT INTO files VALUES('src/calc.py','2d460782e39ec0c9','9c5cffc6d420e6f74d847e458bb26a213c2e334a');
INSERT INTO files VALUES('src/app.py','8fc9bcd85ed44326','f5def48c571f45ec75456d2cbe536766898a00f3');
INSERT INTO files VALUES('src/util.ts','e92731cb5d2fbb96','2d6c82603c01dbf9a8f4ae31393e276a4723192b');
CREATE TABLE symbols (
  sid      INTEGER PRIMARY KEY AUTOINCREMENT,
  sym      TEXT UNIQUE NOT NULL,  -- the UNIQUE constraint implies an index; no separate idx needed
  gen      INTEGER NOT NULL DEFAULT 0,  -- live-node epoch (M8/DoD-XA4): bumped on reuse-after-delete
  had_node INTEGER NOT NULL DEFAULT 0   -- sticky 1 once a node has EVER existed for this sid; the
                                        -- durable signal that distinguishes a reuse-after-delete
                                        -- (had_node=1, no live node) from a first-ever / edge-only
                                        -- symbol getting its first node (had_node=0, no bump).
);
INSERT INTO symbols VALUES(1,'file . src/calc.py:',0,1);
INSERT INTO symbols VALUES(2,'ts-python . . . src/calc/add().',0,1);
INSERT INTO symbols VALUES(3,'ts-python . . . src/calc/multiply().',0,1);
INSERT INTO symbols VALUES(8,'file . src/app.py:',0,1);
INSERT INTO symbols VALUES(9,'ts-python . . . src/app/Order#',0,1);
INSERT INTO symbols VALUES(10,'ts-python . . . src/app/__init__().',0,1);
INSERT INTO symbols VALUES(12,'ts-python . . . src/app/total().',0,1);
INSERT INTO symbols VALUES(14,'ts-python . . . src/app/main().',0,1);
INSERT INTO symbols VALUES(15,'ts-python . . . import/calc/',0,1);
INSERT INTO symbols VALUES(30,'file . src/util.ts:',0,1);
INSERT INTO symbols VALUES(31,'ts-typescript . . . src/util/Order#',0,1);
INSERT INTO symbols VALUES(32,'ts-typescript . . . src/util/describe().',0,1);
CREATE TABLE nodes (
  symbol                  INTEGER PRIMARY KEY,  -- sid FK → symbols.sid (ADR-002 stable identity)
  name                    TEXT NOT NULL,
  kind                    TEXT NOT NULL,        -- serialized NodeKind (e.g. "function")
  language                TEXT NOT NULL,
  file                    TEXT NOT NULL DEFAULT '', -- repo-relative source file (Wave 2.6 incremental)
  data                    TEXT NOT NULL,        -- full Node as JSON (still carries string SymbolId for round-trip)
  description             TEXT,                -- semantic: what is this symbol? (Semantic linking)
  requirement             TEXT,                -- semantic: requirement this symbol matches/fulfils
  requirement_validated   INTEGER NOT NULL DEFAULT 0, -- semantic: match validated as true (0/1)
  scope                   TEXT NOT NULL DEFAULT ''  -- hierarchical ownership/partition path (root='')
, requirement_validated_by TEXT, requirement_validated_at INTEGER);
INSERT INTO nodes VALUES(1,'src/calc.py','"file"','python','src/calc.py','{"symbol":"file . src/calc.py:","kind":"file","name":"src/calc.py","language":"python","location":{"file":"src/calc.py","span":{"start_byte":0,"end_byte":0,"start_line":0,"start_col":0,"end_line":0,"end_col":0}},"metadata":{}}',NULL,NULL,0,'',NULL,NULL);
INSERT INTO nodes VALUES(2,'add','"function"','python','src/calc.py','{"symbol":"ts-python . . . src/calc/add().","kind":"function","name":"add","language":"python","location":{"file":"src/calc.py","span":{"start_byte":58,"end_byte":116,"start_line":3,"start_col":0,"end_line":5,"end_col":16}},"signature":"def add(a, b):","metadata":{}}',NULL,NULL,0,'',NULL,NULL);
INSERT INTO nodes VALUES(3,'multiply','"function"','python','src/calc.py','{"symbol":"ts-python . . . src/calc/multiply().","kind":"function","name":"multiply","language":"python","location":{"file":"src/calc.py","span":{"start_byte":119,"end_byte":259,"start_line":8,"start_col":0,"end_line":13,"end_col":16}},"signature":"def multiply(a, b):","metadata":{}}',NULL,NULL,0,'',NULL,NULL);
INSERT INTO nodes VALUES(8,'src/app.py','"file"','python','src/app.py','{"symbol":"file . src/app.py:","kind":"file","name":"src/app.py","language":"python","location":{"file":"src/app.py","span":{"start_byte":0,"end_byte":0,"start_line":0,"start_col":0,"end_line":0,"end_col":0}},"metadata":{}}',NULL,NULL,0,'',NULL,NULL);
INSERT INTO nodes VALUES(9,'Order','"class"','python','src/app.py','{"symbol":"ts-python . . . src/app/Order#","kind":"class","name":"Order","language":"python","location":{"file":"src/app.py","span":{"start_byte":81,"end_byte":327,"start_line":5,"start_col":0,"end_line":15,"end_col":21}},"signature":"class Order:","metadata":{}}',NULL,NULL,0,'',NULL,NULL);
INSERT INTO nodes VALUES(10,'__init__','"function"','python','src/app.py','{"symbol":"ts-python . . . src/app/__init__().","kind":"function","name":"__init__","language":"python","location":{"file":"src/app.py","span":{"start_byte":139,"end_byte":195,"start_line":8,"start_col":4,"end_line":9,"end_col":28}},"signature":"def __init__(self, status):","metadata":{}}',NULL,NULL,0,'',NULL,NULL);
INSERT INTO nodes VALUES(12,'total','"function"','python','src/app.py','{"symbol":"ts-python . . . src/app/total().","kind":"function","name":"total","language":"python","location":{"file":"src/app.py","span":{"start_byte":201,"end_byte":327,"start_line":11,"start_col":4,"end_line":15,"end_col":21}},"signature":"def total(self, prices):","metadata":{}}',NULL,NULL,0,'',NULL,NULL);
INSERT INTO nodes VALUES(14,'main','"function"','python','src/app.py','{"symbol":"ts-python . . . src/app/main().","kind":"function","name":"main","language":"python","location":{"file":"src/app.py","span":{"start_byte":330,"end_byte":427,"start_line":18,"start_col":0,"end_line":21,"end_col":25}},"signature":"def main():","metadata":{}}',NULL,NULL,0,'',NULL,NULL);
INSERT INTO nodes VALUES(15,'calc','"import"','python','src/app.py','{"symbol":"ts-python . . . import/calc/","kind":"import","name":"calc","language":"python","location":{"file":"src/app.py","span":{"start_byte":53,"end_byte":57,"start_line":2,"start_col":5,"end_line":2,"end_col":9}},"signature":"calc","metadata":{}}',NULL,NULL,0,'',NULL,NULL);
INSERT INTO nodes VALUES(30,'src/util.ts','"file"','typescript','src/util.ts','{"symbol":"file . src/util.ts:","kind":"file","name":"src/util.ts","language":"typescript","location":{"file":"src/util.ts","span":{"start_byte":0,"end_byte":0,"start_line":0,"start_col":0,"end_line":0,"end_col":0}},"metadata":{}}',NULL,NULL,0,'',NULL,NULL);
INSERT INTO nodes VALUES(31,'Order','"interface"','typescript','src/util.ts','{"symbol":"ts-typescript . . . src/util/Order#","kind":"interface","name":"Order","language":"typescript","location":{"file":"src/util.ts","span":{"start_byte":7,"end_byte":44,"start_line":0,"start_col":7,"end_line":2,"end_col":1}},"signature":"interface Order {","metadata":{}}',NULL,NULL,0,'',NULL,NULL);
INSERT INTO nodes VALUES(32,'describe','"function"','typescript','src/util.ts','{"symbol":"ts-typescript . . . src/util/describe().","kind":"function","name":"describe","language":"typescript","location":{"file":"src/util.ts","span":{"start_byte":53,"end_byte":122,"start_line":4,"start_col":7,"end_line":6,"end_col":1}},"signature":"function describe(o: Order): string {","metadata":{}}',NULL,NULL,0,'',NULL,NULL);
CREATE TABLE edges (
  source         INTEGER NOT NULL,   -- sid FK → symbols.sid (dependent, edge-direction invariant)
  target         INTEGER NOT NULL,   -- sid FK → symbols.sid (dependency)
  kind           TEXT NOT NULL,      -- serialized EdgeKind (e.g. "calls")
  confidence     REAL NOT NULL,
  file           TEXT NOT NULL DEFAULT '', -- repo-relative source file of the edge site (Wave 2.6)
  data           TEXT NOT NULL,      -- full Edge as JSON (still carries string SymbolIds for round-trip)
  evidence_count INTEGER NOT NULL DEFAULT 0, -- queryable mirror of the first-class Edge.evidence_count field (brain consolidation)
  PRIMARY KEY (source, target, kind)
);
INSERT INTO edges VALUES(1,2,'"contains"',1.0,'src/calc.py','{"source":"file . src/calc.py:","target":"ts-python . . . src/calc/add().","kind":"contains","confidence":1.0,"provenance":"parsed","resolved_by":"tree-sitter","evidence_count":0,"location":{"file":"src/calc.py","span":{"start_byte":0,"end_byte":0,"start_line":0,"start_col":0,"end_line":0,"end_col":0}},"metadata":{}}',0);
INSERT INTO edges VALUES(1,3,'"contains"',1.0,'src/calc.py','{"source":"file . src/calc.py:","target":"ts-python . . . src/calc/multiply().","kind":"contains","confidence":1.0,"provenance":"parsed","resolved_by":"tree-sitter","evidence_count":0,"location":{"file":"src/calc.py","span":{"start_byte":0,"end_byte":0,"start_line":0,"start_col":0,"end_line":0,"end_col":0}},"metadata":{}}',0);
INSERT INTO edges VALUES(8,9,'"contains"',1.0,'src/app.py','{"source":"file . src/app.py:","target":"ts-python . . . src/app/Order#","kind":"contains","confidence":1.0,"provenance":"parsed","resolved_by":"tree-sitter","evidence_count":0,"location":{"file":"src/app.py","span":{"start_byte":0,"end_byte":0,"start_line":0,"start_col":0,"end_line":0,"end_col":0}},"metadata":{}}',0);
INSERT INTO edges VALUES(8,10,'"contains"',1.0,'src/app.py','{"source":"file . src/app.py:","target":"ts-python . . . src/app/__init__().","kind":"contains","confidence":1.0,"provenance":"parsed","resolved_by":"tree-sitter","evidence_count":0,"location":{"file":"src/app.py","span":{"start_byte":0,"end_byte":0,"start_line":0,"start_col":0,"end_line":0,"end_col":0}},"metadata":{}}',0);
INSERT INTO edges VALUES(8,12,'"contains"',1.0,'src/app.py','{"source":"file . src/app.py:","target":"ts-python . . . src/app/total().","kind":"contains","confidence":1.0,"provenance":"parsed","resolved_by":"tree-sitter","evidence_count":0,"location":{"file":"src/app.py","span":{"start_byte":0,"end_byte":0,"start_line":0,"start_col":0,"end_line":0,"end_col":0}},"metadata":{}}',0);
INSERT INTO edges VALUES(8,14,'"contains"',1.0,'src/app.py','{"source":"file . src/app.py:","target":"ts-python . . . src/app/main().","kind":"contains","confidence":1.0,"provenance":"parsed","resolved_by":"tree-sitter","evidence_count":0,"location":{"file":"src/app.py","span":{"start_byte":0,"end_byte":0,"start_line":0,"start_col":0,"end_line":0,"end_col":0}},"metadata":{}}',0);
INSERT INTO edges VALUES(8,15,'"imports"',1.0,'src/app.py','{"source":"file . src/app.py:","target":"ts-python . . . import/calc/","kind":"imports","confidence":1.0,"provenance":"parsed","resolved_by":"tree-sitter","evidence_count":0,"location":{"file":"src/app.py","span":{"start_byte":53,"end_byte":57,"start_line":2,"start_col":5,"end_line":2,"end_col":9}},"metadata":{}}',0);
INSERT INTO edges VALUES(30,31,'"contains"',1.0,'src/util.ts','{"source":"file . src/util.ts:","target":"ts-typescript . . . src/util/Order#","kind":"contains","confidence":1.0,"provenance":"parsed","resolved_by":"tree-sitter","evidence_count":0,"location":{"file":"src/util.ts","span":{"start_byte":0,"end_byte":0,"start_line":0,"start_col":0,"end_line":0,"end_col":0}},"metadata":{}}',0);
INSERT INTO edges VALUES(30,32,'"contains"',1.0,'src/util.ts','{"source":"file . src/util.ts:","target":"ts-typescript . . . src/util/describe().","kind":"contains","confidence":1.0,"provenance":"parsed","resolved_by":"tree-sitter","evidence_count":0,"location":{"file":"src/util.ts","span":{"start_byte":0,"end_byte":0,"start_line":0,"start_col":0,"end_line":0,"end_col":0}},"metadata":{}}',0);
INSERT INTO edges VALUES(14,12,'"calls"',0.6499999761581420898,'src/app.py','{"source":"ts-python . . . src/app/main().","target":"ts-python . . . src/app/total().","kind":"calls","confidence":0.65,"provenance":"import_map","resolved_by":"scoped-name-resolver","evidence_count":0,"location":{"file":"src/app.py","span":{"start_byte":384,"end_byte":389,"start_line":20,"start_col":16,"end_line":20,"end_col":21}},"metadata":{"scope":"same-file"}}',0);
INSERT INTO edges VALUES(14,3,'"calls"',0.6299999952316284179,'src/app.py','{"source":"ts-python . . . src/app/main().","target":"ts-python . . . src/calc/multiply().","kind":"calls","confidence":0.63,"provenance":"import_map","resolved_by":"import-map-resolver","evidence_count":0,"location":{"file":"src/app.py","span":{"start_byte":412,"end_byte":420,"start_line":21,"start_col":10,"end_line":21,"end_col":18}},"metadata":{"via":"import-map"}}',0);
INSERT INTO edges VALUES(3,2,'"calls"',0.6499999761581420898,'src/calc.py','{"source":"ts-python . . . src/calc/multiply().","target":"ts-python . . . src/calc/add().","kind":"calls","confidence":0.65,"provenance":"import_map","resolved_by":"scoped-name-resolver","evidence_count":0,"location":{"file":"src/calc.py","span":{"start_byte":229,"end_byte":232,"start_line":12,"start_col":16,"end_line":12,"end_col":19}},"metadata":{"scope":"same-file"}}',0);
INSERT INTO edges VALUES(12,2,'"calls"',0.6299999952316284179,'src/app.py','{"source":"ts-python . . . src/app/total().","target":"ts-python . . . src/calc/add().","kind":"calls","confidence":0.63,"provenance":"import_map","resolved_by":"import-map-resolver","evidence_count":0,"location":{"file":"src/app.py","span":{"start_byte":291,"end_byte":294,"start_line":14,"start_col":21,"end_line":14,"end_col":24}},"metadata":{"via":"import-map"}}',0);
CREATE TABLE unresolved_refs (
  id       INTEGER PRIMARY KEY,
  from_sym INTEGER NOT NULL,     -- sid FK → symbols.sid of the referencing symbol
  raw_name TEXT NOT NULL,        -- the written name at the call/import site
  kind     TEXT NOT NULL,        -- serialized EdgeKind (same encoding as edges.kind)
  file     TEXT NOT NULL DEFAULT '', -- repo-relative source file (Wave 2.6 incremental)
  line     INTEGER NOT NULL DEFAULT 0 -- start_line of the reference site
);
INSERT INTO unresolved_refs VALUES(1,3,'range','"calls"','src/calc.py',11);
INSERT INTO unresolved_refs VALUES(2,14,'Order','"calls"','src/app.py',19);
INSERT INTO unresolved_refs VALUES(3,14,'print','"calls"','src/app.py',20);
INSERT INTO unresolved_refs VALUES(4,14,'print','"calls"','src/app.py',21);
CREATE TABLE meta (
  k TEXT PRIMARY KEY,
  v TEXT NOT NULL
);
INSERT INTO meta VALUES('graph_version','1');
INSERT INTO meta VALUES('indexed_root','tests/fixtures/estate_repo');
INSERT INTO meta VALUES('indexed_version','0.14.4');
INSERT INTO meta VALUES('repo_commit','');
INSERT INTO meta VALUES('repo_branch','');
INSERT INTO meta VALUES('repo_remote','');
INSERT INTO meta VALUES('repo_dirty','0');
COMMIT;
